title:              Jake Bowden
tagline:
description:
url:                http://jbwdn.github.io

author:
  name:             Jake Bowden
  url:              https://twitter.com/bwdn_j
  email:            jakebowden@pm.me

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
